### ISSUE TITLE
Can't access docker image using 127.0.0.1

### ISSUE THREAD

**Issue by cryoff** [infinohq/infino#200]
Hello!
I tried to use both the provided `docker` image and tried to build a new one using the provided `Dockerfile`: I have no luck accessing it at `localhost:3000` (or 127.0.0.1 or 0.0.0.0) under ubuntu 20.04. I get `connection reset` error.

After it I changed all the configs to hardcode `0.0.0.0` instead of `127.0.0.1` but then server is running but just not accepting connections: I am getting 404. 

Do you have any recommendations on what can be done?

**Comment by vinaykakade** [comment]
Thanks for reporting. We are on it. Can you please check if the port being used by Infino (default `3000`) is available from outside docker in your setup? 

Regarding server running but returning 404, please check the path `/ping`. The path `/` returns a 404 today - will be making a change shortly so that it doesn't return 404.

FWIW, a way to unblock if you have Rust toolchain installed is to checkout the repo and start the server by running `make run`.

**Comment by santhoshsram** [comment]
Hi,
Appreciate you trying infino and reporting this. We'll update infino to provide a helpful response when a request hits the `/` path.

Meanwhile, another option to make infino listen on a non localhost address is to override the default config of `host=127.0.0.1` in `config/default.toml` using below steps.

1. Create a toml file locally (say `dev.toml` for example) and add the below config to it.
```
[server]
host = 0.0.0.0
```
Note: You can change 0.0.0.0 to any valid address.

2. Run the container with the env var `RUN_MODE=dev` (the mode should match the toml file name) and mount the config file to /opt/infino/dev.toml in the contianer.
```
docker run -it --rm --env RUN_MODE=dev -v <path/to/dev.toml>:/opt/infino/config/dev.toml -p 3000:3000 infinohq/infino:latest
```

3. `curl http://localhost:3000/ping` should now return `OK`.

**Comment by cryoff** [comment]
Thank you, I pulled the latest image and now it runs like a charm (probably it was running before but 404 on "/" root was misleading : ))

**Comment by santhoshsram** [comment]
Glad to know that! Please do share any feedback or requests you may have.
